apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-premium
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: premium
  network: primary-vault-vpc
